services:
  database:
    image: postgres:17
    container_name: finContainer
    restart: no
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
